### ISSUE TITLE
Does JS binding work?

### ISSUE THREAD

**Issue by duyk16** [Chia-Network/bls-signatures#220] opened 2021-05-24 16:53 UTC
Does JS binding work? I don't see some classes like G1Element, G2Element, ... in typescript definition

**Comment by ChiaMineJP** [comment] 2021-06-09 04:53
Looks like blsjs.d.ts was created 2yrs ago...
I confirmed that actual blsjs.js file contains either G1Element, G2Element. Only type definition needs to be fixed.

**Comment by emlowe** [comment] 2021-06-15 21:51
#227 has been merged in - closing issue

**Closed by emlowe** 2021-06-15 21:51 UTC
