### ISSUE TITLE
Build fails on Fedora 34

### ISSUE THREAD

**Issue by ckti** [Chia-Network/bls-signatures#209] opened 2021-04-22 09:37 UTC
Cannot compile on Fedora 34 keep getting the below error...I know Fedora 34 is not in production yet, but I'm planning ahead for its release.  This software has always compiled successfully on Fedora releases up to 34.
```
mkdir build
cmake ../
cmake --build . -- -j1
...

[ 72%] Building C object contrib/relic/src/CMakeFiles/relic_s.dir/md/blake2s-ref.c.o
In file included from /home/ckti/chia_bls/v20181101-1a98518eff9/contrib/relic/src/md/blake2s-ref.c:18:
/home/ckti/chia_bls/v20181101-1a98518eff9/contrib/relic/src/md/blake2.h:101:5: error: size of array element is not a multiple of its alignment
  101 |     blake2s_state S[8][1];
      |     ^~~~~~~~~~~~~
/home/ckti/chia_bls/v20181101-1a98518eff9/contrib/relic/src/md/blake2.h:102:5: error: size of array element is not a multiple of its alignment
  102 |     blake2s_state R[1];
      |     ^~~~~~~~~~~~~
/home/ckti/chia_bls/v20181101-1a98518eff9/contrib/relic/src/md/blake2.h:109:5: error: size of array element is not a multiple of its alignment
  109 |     blake2b_state S[4][1];
      |     ^~~~~~~~~~~~~
/home/ckti/chia_bls/v20181101-1a98518eff9/contrib/relic/src/md/blake2.h:110:5: error: size of array element is not a multiple of its alignment
  110 |     blake2b_state R[1];
      |     ^~~~~~~~~~~~~
/home/ckti/chia_bls/v20181101-1a98518eff9/contrib/relic/src/md/blake2s-ref.c: In function 'blake2s':
/home/ckti/chia_bls/v20181101-1a98518eff9/contrib/relic/src/md/blake2s-ref.c:329:3: error: size of array element is not a multiple of its alignment
  329 |   blake2s_state S[1];
      |   ^~~~~~~~~~~~~
gmake[2]: *** [contrib/relic/src/CMakeFiles/relic_s.dir/build.make:2032: contrib/relic/src/CMakeFiles/relic_s.dir/md/blake2s-ref.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:160: contrib/relic/src/CMakeFiles/relic_s.dir/all] Error 2
gmake: *** [Makefile:149: all] Error 2

```
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,d,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-11.0.1-20210324/obj-x86_64-redhat-linux/isl-install --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.0.1 20210324 (Red Hat 11.0.1-0) (GCC) 

cmake --version
cmake version 3.19.7

CMake suite maintained and supported by Kitware (kitware.com/cmake).

rpm -qi make
Name        : make
Epoch       : 1
Version     : 4.3
Release     : 5.fc34
Architecture: x86_64
Install Date: Wed Apr 21 13:56:33 2021
Group       : Unspecified
Size        : 1729654
License     : GPLv3+
Signature   : RSA/SHA256, Fri Feb 19 20:35:28 2021, Key ID 1161ae6945719a39
Source RPM  : make-4.3-5.fc34.src.rpm
Build Date  : Fri Feb 19 20:33:02 2021
Build Host  : buildhw-x86-14.iad2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : http://www.gnu.org/software/make/
Bug URL     : https://bugz.fedoraproject.org/make
Summary     : A GNU tool which simplifies the build process for users
Description :
A GNU tool for controlling the generation of executables and other
non-source files of a program from the program's source files. Make
allows users to build and install packages without any significant
knowledge about the details of the build process. The details about
how the program should be built are provided for make in the program's
makefile.

**Comment by Chewbakka-Wakka** [comment] 2021-05-23 06:04
I have the same set of errors on the latest V 1.0.1

[ 81%] Building C object _deps/relic-build/src/CMakeFiles/relic_s.dir/md/blake2s-ref.c.o
In file included from /home/ss/rpmbuild/BUILD/blspy-1.0.1/build/temp.linux-x86_64-3.8/_deps/relic-src/src/md/blake2s-ref.c:18:
/home/ss/rpmbuild/BUILD/blspy-1.0.1/build/temp.linux-x86_64-3.8/_deps/relic-src/src/md/blake2.h:101:5: error: size of array element is not a multiple of its alignment
  101 |     blake2s_state S[8][1];
      |     ^~~~~~~~~~~~~
/home/ss/rpmbuild/BUILD/blspy-1.0.1/build/temp.linux-x86_64-3.8/_deps/relic-src/src/md/blake2.h:102:5: error: size of array element is not a multiple of its alignment
  102 |     blake2s_state R[1];
      |     ^~~~~~~~~~~~~
/home/ss/rpmbuild/BUILD/blspy-1.0.1/build/temp.linux-x86_64-3.8/_deps/relic-src/src/md/blake2.h:109:5: error: size of array element is not a multiple of its alignment
  109 |     blake2b_state S[4][1];
      |     ^~~~~~~~~~~~~
/home/ss/rpmbuild/BUILD/blspy-1.0.1/build/temp.linux-x86_64-3.8/_deps/relic-src/src/md/blake2.h:110:5: error: size of array element is not a multiple of its alignment
  110 |     blake2b_state R[1];
      |     ^~~~~~~~~~~~~
[ 81%] Building C object _deps/relic-build/src/CMakeFiles/relic_s.dir/md/relic_md_blake2s.c.o
/home/ss/rpmbuild/BUILD/blspy-1.0.1/build/temp.linux-x86_64-3.8/_deps/relic-src/src/md/blake2s-ref.c: In function ‘blake2s’:
/home/ss/rpmbuild/BUILD/blspy-1.0.1/build/temp.linux-x86_64-3.8/_deps/relic-src/src/md/blake2s-ref.c:329:3: error: size of array element is not a multiple of its alignment
  329 |   blake2s_state S[1];
      |   ^~~~~~~~~~~~~
gmake[2]: *** [_deps/relic-build/src/CMakeFiles/relic_s.dir/build.make:2834: _deps/relic-build/src/CMakeFiles/relic_s.dir/md/blake2s-ref.c.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
In file included from /home/ss/rpmbuild/BUILD/blspy-1.0.1/build/temp.linux-x86_64-3.8/_deps/relic-src/src/md/relic_md_blake2s.c:38:
/home/ss/rpmbuild/BUILD/blspy-1.0.1/build/temp.linux-x86_64-3.8/_deps/relic-src/src/md/blake2.h:101:5: error: size of array element is not a multiple of its alignment
  101 |     blake2s_state S[8][1];
      |     ^~~~~~~~~~~~~
/home/ss/rpmbuild/BUILD/blspy-1.0.1/build/temp.linux-x86_64-3.8/_deps/relic-src/src/md/blake2.h:102:5: error: size of array element is not a multiple of its alignment
  102 |     blake2s_state R[1];
      |     ^~~~~~~~~~~~~
/home/ss/rpmbuild/BUILD/blspy-1.0.1/build/temp.linux-x86_64-3.8/_deps/relic-src/src/md/blake2.h:109:5: error: size of array element is not a multiple of its alignment
  109 |     blake2b_state S[4][1];
      |     ^~~~~~~~~~~~~
/home/ss/rpmbuild/BUILD/blspy-1.0.1/build/temp.linux-x86_64-3.8/_deps/relic-src/src/md/blake2.h:110:5: error: size of array element is not a multiple of its alignment
  110 |     blake2b_state R[1];
      |     ^~~~~~~~~~~~~
gmake[2]: *** [_deps/relic-build/src/CMakeFiles/relic_s.dir/build.make:2848: _deps/relic-build/src/CMakeFiles/relic_s.dir/md/relic_md_blake2s.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:306: _deps/relic-build/src/CMakeFiles/relic_s.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2

**Comment by madMAx43v3r** [comment] 2021-06-08 09:20
use gcc version <11

**Comment by ckti** [comment] 2021-06-14 09:27
Yeah...not so easy to do on fedora (fedora 34 is now in production)...and ubuntu/debian are catching up and will be gcc > 10 at some point...

**Comment by emlowe** [comment] 2021-06-14 16:13
Duplicate of #194

**Closed by emlowe** 2021-06-14 16:13 UTC
